name: "check-large-file"
description: "Check for large file"
inputs:
  threshold:
    description: "File size upper limit"
    required: false
    default: "4096"
outputs:
  ok:
    description: Whether current commit is acceptable
    value: ${{ false  }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: ./check.sh ${{ inputs.threshold }}
      shell: bash
